name: Get GitHub Info

on:
  release:
    types:
      - created

jobs:
  get-github-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set GitHub Info
        run: |
          echo "VITE_GITHUB_USERNAME=${{ github.actor }}" >> $GITHUB_ENV
          echo "VITE_GITHUB_REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV

          # Extract release tag from the Git reference
          RELEASE_TAG=$(echo "${{ github.ref }}" | sed -n 's|^refs/tags/||p')
          echo "VITE_RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV

      - name: Display GitHub Info
        run: |
          echo "GitHub Username: $VITE_GITHUB_USERNAME"
          echo "GitHub Repo Name: $VITE_GITHUB_REPO_NAME"
          echo "Release Tag: $VITE_RELEASE_TAG"

      - name: Use GitHub Info in Build Step
        run: |
          npm install
          npm run build
        env:
          VITE_GITHUB_USERNAME: ${{ env.VITE_GITHUB_USERNAME }}
          VITE_GITHUB_REPO_NAME: ${{ env.VITE_GITHUB_REPO_NAME }}
          VITE_RELEASE_TAG: ${{ env.VITE_RELEASE_TAG }}
